menu:
  首页: / || fas fa-home
  搜索: /search/ || fas fa-search
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  关于: /about/ || fas fa-heart

favicon: /img/favicon.png
avatar:
  img: /img/avatar.svg
  effect: false

nav:
  fixed: false
  display_title: true

disable_top_img: false
index_img: https://butterfly.js.org/img/index.webp
default_top_img: false
archive_img: false
tag_img: false
category_img: false
footer_bg: false

subtitle:
  enable: true
  effect: false
  sub:
    - Never put off till tomorrow what you can do today

social:
  fab fa-github: https://github.com/sdasdasda111/Blog || Github || '#24292e'

index_site_info_top: 46%
index_top_img_height: 100vh
index_layout: 4
index_post_content:
  method: 2
  length: 180

post_meta:
  page:
    date_type: created
    categories: false
    tags: false
  post:
    date_type: both
    categories: true
    tags: true

aside:
  enable: true
  hide: false
  button: false
  mobile: false
  position: right
  display:
    archive: false
    tag: false
    category: false

card_author:
  enable: true
  description: Linux / Embedded / Debugging
  button:
    enable: false
    icon: fab fa-github
    text: Follow Me
    link: https://github.com/sdasdasda111/Blog

card_announcement:
  enable: false
  content: ''

card_webinfo:
  enable: false
  post_count: false
  last_push_date: false
  sort: 1

local_search:
  enable: true
  preload: false
  CDN:

highlight_theme: mac
code_word_wrap: false
copy:
  enable: true
  copyright:
    enable: false

toc:
  post: true
  page: false
  number: true
  expand: false
  style_simple: true

comments:
  use: false

busuanzi:
  site_uv: false
  site_pv: false
  page_pv: false
