title: Odette
subtitle: Never put off till tomorrow what you can do today
description: 记录 Linux、采集链路、驱动开发、调试分析与系统工程实践。联系方式：13244657856
keywords:
  - linux
  - driver
  - embedded
  - engineering
author: Lorcan dong
language: zh-CN
timezone: Asia/Shanghai
url: https://sdasdasda111.github.io/Blog
root: /Blog/
permalink: posts/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: false

theme: butterfly

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

per_page: 10
pagination_dir: page

marked:
  prependRoot: true
  postAsset: false

index_generator:
  path: ''
  per_page: 10
  order_by: -date

archive_generator:
  per_page: 20
  yearly: true
  monthly: false
  daily: false
  order_by: -date

category_generator:
  per_page: 10

tag_generator:
  per_page: 10

search:
  path: search.xml
  field: post
  content: true
  template: false

deploy:
  type: ''
